"""initial schema

Revision ID: e4a768f106f0
Revises: 
Create Date: 2026-03-14 13:15:48.736020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4a768f106f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditissue',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clause_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_object', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rectification_suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_chain', sa.JSON(), nullable=True),
    sa.Column('contradiction_flags', sa.JSON(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_auditissue_batch_id'), 'auditissue', ['batch_id'], unique=False)
    op.create_index(op.f('ix_auditissue_issue_id'), 'auditissue', ['issue_id'], unique=False)
    op.create_table('auditreport',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('audit_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('issue_list', sa.JSON(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('export_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_auditreport_batch_id'), 'auditreport', ['batch_id'], unique=True)
    op.create_index(op.f('ix_auditreport_report_id'), 'auditreport', ['report_id'], unique=False)
    op.create_table('batchrecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('uploader', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'CLASSIFYING', 'EXTRACTING', 'AUDITING', 'REPORTING', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_counts', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batchrecord_batch_id'), 'batchrecord', ['batch_id'], unique=False)
    op.create_table('equipmentmaster',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inspection_dates', sa.JSON(), nullable=True),
    sa.Column('operator_links', sa.JSON(), nullable=True),
    sa.Column('material_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_index(op.f('ix_equipmentmaster_batch_id'), 'equipmentmaster', ['batch_id'], unique=False)
    op.create_index(op.f('ix_equipmentmaster_equipment_id'), 'equipmentmaster', ['equipment_id'], unique=False)
    op.create_table('evidenceitem',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=True),
    sa.Column('field_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clause_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidenceitem_batch_id'), 'evidenceitem', ['batch_id'], unique=False)
    op.create_index(op.f('ix_evidenceitem_evidence_id'), 'evidenceitem', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidenceitem_file_id'), 'evidenceitem', ['file_id'], unique=False)
    op.create_table('extractionrecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_model_json', sa.JSON(), nullable=True),
    sa.Column('validated_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_index(op.f('ix_extractionrecord_extraction_id'), 'extractionrecord', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extractionrecord_file_id'), 'extractionrecord', ['file_id'], unique=False)
    op.create_table('filerecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_groups', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification_evidence', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_filerecord_batch_id'), 'filerecord', ['batch_id'], unique=False)
    op.create_index(op.f('ix_filerecord_file_id'), 'filerecord', ['file_id'], unique=False)
    op.create_table('personmaster',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_no_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certs', sa.JSON(), nullable=True),
    sa.Column('medical_validity', sa.Date(), nullable=True),
    sa.Column('insurance_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employment_links', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_personmaster_batch_id'), 'personmaster', ['batch_id'], unique=False)
    op.create_index(op.f('ix_personmaster_person_id'), 'personmaster', ['person_id'], unique=False)
    op.create_table('projectprofile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('section_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contractor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projectprofile_batch_id'), 'projectprofile', ['batch_id'], unique=False)
    op.create_index(op.f('ix_projectprofile_project_id'), 'projectprofile', ['project_id'], unique=False)
    op.create_table('ruledefinition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clause_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_object', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_required', sa.Integer(), nullable=False),
    sa.Column('logic_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rectification_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruledefinition_id'), 'ruledefinition', ['id'], unique=False)
    op.create_index(op.f('ix_ruledefinition_rule_id'), 'ruledefinition', ['rule_id'], unique=True)
    op.create_table('ruleexecutionresult',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('related_file_ids', sa.JSON(), nullable=True),
    sa.Column('related_pages', sa.JSON(), nullable=True),
    sa.Column('generated_issue_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_ruleexecutionresult_batch_id'), 'ruleexecutionresult', ['batch_id'], unique=False)
    op.create_index(op.f('ix_ruleexecutionresult_execution_id'), 'ruleexecutionresult', ['execution_id'], unique=False)
    op.create_index(op.f('ix_ruleexecutionresult_rule_id'), 'ruleexecutionresult', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ruleexecutionresult_rule_id'), table_name='ruleexecutionresult')
    op.drop_index(op.f('ix_ruleexecutionresult_execution_id'), table_name='ruleexecutionresult')
    op.drop_index(op.f('ix_ruleexecutionresult_batch_id'), table_name='ruleexecutionresult')
    op.drop_table('ruleexecutionresult')
    op.drop_index(op.f('ix_ruledefinition_rule_id'), table_name='ruledefinition')
    op.drop_index(op.f('ix_ruledefinition_id'), table_name='ruledefinition')
    op.drop_table('ruledefinition')
    op.drop_index(op.f('ix_projectprofile_project_id'), table_name='projectprofile')
    op.drop_index(op.f('ix_projectprofile_batch_id'), table_name='projectprofile')
    op.drop_table('projectprofile')
    op.drop_index(op.f('ix_personmaster_person_id'), table_name='personmaster')
    op.drop_index(op.f('ix_personmaster_batch_id'), table_name='personmaster')
    op.drop_table('personmaster')
    op.drop_index(op.f('ix_filerecord_file_id'), table_name='filerecord')
    op.drop_index(op.f('ix_filerecord_batch_id'), table_name='filerecord')
    op.drop_table('filerecord')
    op.drop_index(op.f('ix_extractionrecord_file_id'), table_name='extractionrecord')
    op.drop_index(op.f('ix_extractionrecord_extraction_id'), table_name='extractionrecord')
    op.drop_table('extractionrecord')
    op.drop_index(op.f('ix_evidenceitem_file_id'), table_name='evidenceitem')
    op.drop_index(op.f('ix_evidenceitem_evidence_id'), table_name='evidenceitem')
    op.drop_index(op.f('ix_evidenceitem_batch_id'), table_name='evidenceitem')
    op.drop_table('evidenceitem')
    op.drop_index(op.f('ix_equipmentmaster_equipment_id'), table_name='equipmentmaster')
    op.drop_index(op.f('ix_equipmentmaster_batch_id'), table_name='equipmentmaster')
    op.drop_table('equipmentmaster')
    op.drop_index(op.f('ix_batchrecord_batch_id'), table_name='batchrecord')
    op.drop_table('batchrecord')
    op.drop_index(op.f('ix_auditreport_report_id'), table_name='auditreport')
    op.drop_index(op.f('ix_auditreport_batch_id'), table_name='auditreport')
    op.drop_table('auditreport')
    op.drop_index(op.f('ix_auditissue_issue_id'), table_name='auditissue')
    op.drop_index(op.f('ix_auditissue_batch_id'), table_name='auditissue')
    op.drop_table('auditissue')
    # ### end Alembic commands ###
