from enum import Enum


class BatchStatus(str, Enum):
    UPLOADED = "UPLOADED"
    CLASSIFYING = "CLASSIFYING"
    EXTRACTING = "EXTRACTING"
    AUDITING = "AUDITING"
    REPORTING = "REPORTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AuditGroup(str, Enum):
    PROJECT_ADMISSION_LEGAL = "PROJECT_ADMISSION_LEGAL"
    PERSONNEL_CONSISTENCY_QUALIFICATION = "PERSONNEL_CONSISTENCY_QUALIFICATION"
    HSE_RISK_DOCUMENTS = "HSE_RISK_DOCUMENTS"
    EQUIPMENT_TOOLS_MATERIALS = "EQUIPMENT_TOOLS_MATERIALS"
    TRAINING_PERMIT_CLOSURE = "TRAINING_PERMIT_CLOSURE"
    CROSS_DOCUMENT_CONFLICT_SCAN = "CROSS_DOCUMENT_CONFLICT_SCAN"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RuleResult(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    WARN = "WARN"


class LLMMode(str, Enum):
    AUTO = "auto"
    GEMINI = "gemini"
    MOCK = "mock"
